name: JSMR-Spring CI with Gradle

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/*

env:
  JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkouk
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash